### ISSUE TITLE
Instagram Shortcut Error

### ISSUE THREAD

**Issue by KarmaJamms** [voidpet/bugs#24]
Upon cliciking the Instagram shortcut which pops up after entering my Insta username, it brings me to a error page that says "Oops, an error occurred."  I think it must be a site problem since it doesn't say "nonexistent user" or anything like that, but I could be mistaken.

**Comment by benawad** [comment]
what's your instagram handle and voidpet username, I'll take a look at it

**Comment by KarmaJamms** [comment]
_karmajam on Instagram and karmajam on voidpet

**Comment by amitojsingh366** [comment]
I had this error aswell, this is due to poor route handling by Instagram. @benawad if you change the default url for Instagram from `https://instagram.com/<USERNAME>` to `https://www.instagram.com/<USERNAME>/` *(the trailing `/` is intended)* It should fix this issue, at least that's what worked for me

**Comment by amitojsingh366** [comment]
also note this error only happens when you haven't opened the Instagram webapp recently. if you have opened it fairly recently it wont show the error page and Instead will take you to the profile as intended

**Comment by benawad** [comment]
done
