### ISSUE TITLE
My voidpet won’t gain xp 

### ISSUE THREAD

**Issue by Suckmytoes21** [voidpet/bugs#353]
Hello!
After I win a fight my voidpet won’t gain xp to level up. For context it’s a sad, it’s at level 5, and it’s the lead voidpet on the team. It is not a vivid.

I play on an iOS 8+.

**Comment by tastryan** [comment]
Hey, just so you know, this is just because the game is still in development! It's on the Voidpet discord in the announcement channel, and it mentions that the level cap is level 5, so until there is another update, your voidpets can only get to level 5. 
I've included a screenshot in case you don't have discord or can't access it. 

<img width="847" alt="Screen Shot 2022-04-08 at 7 39 28 PM" src="https://user-images.githubusercontent.com/103155039/162546865-6d63c73a-0a8d-44f6-9ab1-a7e383c83abe.png">
'
